services:
  api:
    image: ghcr.io/y4nn777/tenglaafi:latest
    container_name: tenglaafi_api
    env_file: .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8000:8000"  # Ã©coute locale; Nginx sera en frontal
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3000s
      timeout: 5s
      retries: 5